[0_(1)=TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>TK consensus 
{()LKLGKVLGEGAFGEVYKGTLKGPGGTTIPVAVKTLKEGASEQERRDFLSEAKIMKQLDHPNIVRLLGVCTEGGPLYIVTEYMENGDLLDFLRKNRPPGPLTLKQLLDMAYQIASGMEYLESKNFVHRDLAARNCLVGENLVVKIADFGLARDIYDDDYYTARGGGKLPIKWMAPEAINYGKFTSKSDVWSFGVLLWEIFTLGEQPYPGMSNQEVLEAVEEGYRLPQPENCPDELYELMLQCWQKDPEDRPTFSQLVEFLED()}*

$2=256(261):
>XP_004993304.1  {|269(174)|}TK/ABL protein kinase [Salpingoeca rosetta] 
{()IKMGRKLGAGQYGEVYEGVWT---AHQRRIAVKTLKEGSMDVK--DFLKEANVMKKLKHENLVQLIGICTRETPLFIITEFMPRGNLLDYLRNQDaQ-KEIDPTAMMYIAAQVASGMAYLEQHNYIHRDLAARNCLVGENLTVKLADFGLARLLQVEDPYTAKEGSKFPIKWTAPESLSFNRFTIKSDVWAFGICLWEIATLGSTPYPGMDLYTVLDRLDAGYRMPRPEGCPAEVYQLMRDCWQQDPNDRPAFKDIRRRLES()}*

_0].
[0_(1)=FPVR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>FPVR_TK consensus 
{()LVLGKTLGEGAFGQVVEATAFGIDDACMTVAVKMLKETATSSEKEALMSELKIMKHLHHLNIVNLLGACTQGGPLYVIVEYCCYGNLRNFLRRKRDEEPLTLEDLLSFSYQVARGMEFLASKKCIHRDLAARNVLVTEGNVVKICDFGLARDIMNDSNYVKKGNARLPVKWMAPESIFDRVYTTQSDVWSFGILLWEIFSLGGSPYPGIPVDEFYKLLKEGYRMDQPEHATEEIYQIMQSCWHADPSKRPTFKQLVEDLED()}*

$2=376(261):
>KFM76603.1  {|865(172)|}Vascular endothelial growth factor receptor 3, partial [Stegodyphus mimosarum] 
{()LKLGKTLGQGAFGRVVKAEAIGLIdgEASTTVAVKMLKEAADAEQRKALIAELKILIHIgRHLNIVNLLGAVTKnvaKGELYVIVEYCCFGNLRHFLLKHKGtfidqldhqsgqldptistlpgspflnikdnmavysnilgiamdnptyseqslnyadlahqqvtndsgtgisvltnpsgssindryfrnsfshspvgcsseccneelaKNHfITTCDLLCFAFQCARGMEYLASRKLIHRDLAARNVLLAKDNVVKICDFGLAKDCYKYSNYIKKSDGLLPIKWMAIESIRDRVYTSKSDVWSFGILLWEIFTLGSNPYPGIEINEeFFKKLKNGYRMEKPDLAPDKIYNLMKNCWLDDPNQRPDFTYLAENIG-()}*

_0].
[0_(1)=Ret_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Ret_TK consensus 
{()LQLGKTLGEGEFGQVVKATAFHIKAGYTTVAVKMLKENASSSELRDLLSEFNLLKQVNHPHVIKLYGACSQDGPLCLIVEYAKYGSLRGFLRDSRKERPITMGDIISFAWQICQGMQYLAEMKLVHRDLAARNILVAEGRKMKISDFGLTRDVYEEDSYVKQSQGRIPVKWMAIESLFDHIYTTQSDVWSFGVLLWEIVTLGANPYPGIPPERLCNLLKTGHRMDRPDNCSEEMYRIMRQCWKQEPDKRPVFADISKDFEK()}*

$2=284(261):
>CAA39792.1  {|86(65)|}urf-ret [Homo sapiens] 
{()LVLGKTLGEGEFGKVVKATAFHLKgrAGYTTVAVKMLKENASPSELRDLLSEFNVLKQVNHPHVIKLYGACSQDGPLLLIVEYAKYGSLRGFLRESRKvgpgylgsggsrnsssldhpdERALTMGDLISFAWQISQGMQYLAEMKLVHRDLAARNILVAEGRKMKISDFGLSRDVYEEDSYVKRSQGRIPVKWMAIESLFDHIYTTQSDVWSFGVLLWEIVTLGGNPYPGIPPERLFNLLKTGHRMERPDNCSEEMYRLMLQCWKQEPDKRPVFADISKDLEK()}*

_0].
[0_(1)=FGFR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>FGFR_TK consensus 
{()LTLGKPLGEGCFGQVVMAEAIGIDNQATTVAVKMLKDDATDKDLSDLVSEMEMMKMIKHKNIINLLGACTQDGPLYVIVEYASKGNLREFLRARRPEEQLTFKDLVSCAYQVARGMEYLASQKCIHRDLAARNVLVTEDNVMKIADFGLARDIHHIDYYKKTTNGRLPVKWMAPEALFDRVYTHQSDVWSFGVLLWEIFTLGGSPYPGIPVEELFKLLKEGHRMDKPANCTNELYMMMRECWHAVPSQRPTFKQLVEDLDR()}*

$2=279(261):
>XP_027555674.1  {|489(62)|}fibroblast growth factor receptor 3 isoform X2 [Neopelma chrysocephalum] 
{()LTLGKPLGEGCFGQVVMAEAIGIDkdkpNKAVTVAVKMLKDDATDKDLSDLVSEMEMMKMIgKHKNIINLLGACTQDGPLYVLVEYASKGNLREYLRARRPpgmdysfdtcklpEEQLTFKDLVSCAYQVARGMEYLASQKCIHRDLAARNVLVTEDNVMKIADFGLARDVHNIDYYKKTTNGRLPVKWMAPEALFDRVYTHQSDVWSFGVLLWEIFTLGGSPYPGIPVEELFKLLKEGHRMDKPANCTHDLYMIMRECWHAVPSQRPTFKQLVEDLDR()}*

_0].
[0_(1)=PVR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>PVR_TK consensus 
{()LKLGKTLGSGAFGKVVEATAFGISDACMTVAVKMLKETATSSEKEALMSELKIMTHLHHLNIVNLLGACTKGGPIYVITEYCCYGDLLNYLRRKRDSNPLTLEDLLCFSYQVARGMEFLASKNCIHRDLAARNVLLTEGKVVKICDFGLARDIMNDSNYVVKGNARLPVKWMAPESIFDCVYTTQSDVWSYGILLWEIFSLGGSPYPGVPVDEFYKRIKEGYRMAQPEYATPEIYQIMQSCWDGDPEKRPTFSQLVEFLGD()}*

$2=325(261):
>XP_007906314.1  {|395(43)|}PREDICTED: macrophage colony-stimulating factor 1 receptor-like [Callorhinchus milii] 
{()LCFGKILGAGAFGKVMEATAYGLGeeETGTKVAVKMLKPRAHSTEKEALMSELKILSHLgQHNNVVNLLGACTQGGPVLVITEYCCYGDLLNYLK-HRAeyltsssqcsdyrnlcmwppervergksydgylpmrpsvssncplipeidckitdddvleAEetlALDMEQLLNISHQVAHGMDFLSSRNCIHRDVAARNVLLTHGRVAKICDFGLARDIMNDSNYVVKGNARLPVKWMAPESIFDCVYTVQSDVWSYGILLWEIFSLGSSPYPDLPVDSrFYKLIRSGYQMSRPVLGTPEMYDVMSQCWHLDPHKRPTFQQIRQMI--()}*

_0].
[0_(1)=VEGFR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>VEGFR_TK consensus 
{()LKLGKVLGRGAFGKVVEASAFGIDPTCRTVAVKMLKEGATASEHRALMSELKILIHIHHLNVVNLLGACTKGGPLMVIVEFCKYGNLSNYLRSKRDKDPLTMEDLICYSFQVARGMEFLASRKCIHRDLAARNILLSENNVVKICDFGLARDIYKDPDYVRKGDARLPLKWMAPESIFDKVYTTQSDVWSFGVLLWEIFSLGASPYPGVQIDEFCQRLKEGTRMRAPEYATPEIYQTMLDCWHGDPKARPAFSELVEKLGD()}*

$2=326(261):
>XP_006001436.1  {|835(199)|}PREDICTED: vascular endothelial growth factor receptor 2 isoform X1 [Latimeria chalumnae] 
{()LKLGKPLGRGAFGQVVEAAAFGIDklATCKTVAVKMLKEGATSSEHRALMSELKILIHIgHHLNVVNLLGACTKvGGPLMVIVEYCKHGNLSTYLRSKREefvpykskvvkpkqikdkniagevkcrldsiassqssassgfaeekslsdveeqeeeelyKNPLTMEDLICYSFQVARGMEFLASRKCIHRDLAARNILLSENKVVKICDFGLARDVYKDPDYVRKGDARLPLKWMAPETIFDRVYTTQSDVWSFGVLLWEIFSLGASPYPGVQIDEeFCRRLKEGTRMRAPDYATPEVYQTMLDCWHGNPKDRPTFSELVEHLGN()}*

_0].
[0_(1)=PDGFR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>PDGFR_TK consensus 
{()LVLGRTLGSGAFGQVVEATAHGLSQPTMKVAVKMLKPTARSSEKQALMSELKIMTHLPHLNIVNLLGACTKGGPIYIITEYCRYGDLVDYLHRNRHSPVLTYLDLVGFTYQVARGMEFLASKNCVHRDLAARNVLICQGKIVKICDFGLARDIMHDSNYISKGSTFLPVKWMAPESIFDNLYTTLSDVWSFGILLWEIFTLGGTPYPEMMMDQFYNKIKRGYRMAQPDHATDEIYEIMQKCWNEEFEKRPPFYQLVEIVEN()}*

$2=360(261):
>BAD92894.1  {|270(147)|}platelet-derived growth factor receptor beta precursor variant, partial [Homo sapiens] 
{()LVLGRTLGSGAFGQVVEATAHGLShsQATMKVAVKMLKSTARSSEKQALMSELKIMSHLgPHLNVVNLLGACTKGGPIYIITEYCRYGDLVDYLHRNKHtflqhhsdkrrppsaelysnalpvglplpshvsltgesdggymdmskdesvdyvpmldmkgdvkyadiessnymapydnyvpsapertcratlineSPVLSYMDLVGFSYQVANGMEFLASKNCVHRDLAARNVLICEGKLVKICDFGLARDIMRDSNYISKGSTFLPLKWMAPESIFNSLYTTLSDVWSFGILLWEIFTLGGTPYPELPMNeQFYNAIKRGYRMAQPAHASDEIYEIMQKCWEEKFEIRPPFSQLVLLLE-()}*

_0].
[0_(1)=Kit_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Kit_TK consensus 
{()LSFGKTLGAGAFGKVVEATAYGLIDAAMTVAVKMLKPSAHLTEREALMSELKVLSYLNHMNIVNLLGACTIGGPTLVITEYCCYGDLLNFLRRKRDELALDLEDLLSFSYQVAKGMAFLASKNCIHRDLAARNILLTHGRITKICDFGLARDIRNDSNYVVKGNARLPVKWMAPESIFNCVYTFESDVWSYGIFLWELFSLGSSPYPGMPVDKFYKMIKEGFRMVSPEHAPAEMYDIMKTCWDADPLKRPTFKQIVQLIEA()}*

$2=337(261):
>NP_001087241.1  {|584(51)|}mast/stem cell growth factor receptor Kit isoform 2 precursor [Homo sapiens] 
{()LSFGKTLGAGAFGKVVEATAYGLIksDAAMTVAVKMLKPSAHLTEREALMSELKVLSYLgNHMNIVNLLGACTIGGPTLVITEYCCYGDLLNFLRRKRDsficskqedhaeaalyknllhskesscsdstneymdmkpgvsyvvptkadkrrsvrigsyierdvtpaimeddELALDLEDLLSFSYQVAKGMAFLASKNCIHRDLAARNILLTHGRITKICDFGLARDIKNDSNYVVKGNARLPVKWMAPESIFNCVYTFESDVWSYGIFLWELFSLGSSPYPGMPVDsKFYKMIKEGFRMLSPEHAPAEMYDIMKTCWDADPLKRPTFKQIVQLIE-()}*

_0].
[0_(1)=CSF1R_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>CSF1R_TK consensus 
{()LQFGKTLGAGAFGKVVEATAFGLGDAVLKVAVKMLKSTAHADEKEALMSELKIMSHLQHENIVNLLGACTHGGPVLVITEYCCYGDLLNFLRRKAESRPLELWDLLHFSSQVAQGMAFLASKNCIHRDVAARNVLLTNGHVAKIGDFGLARDIMNDSNYIVKGNARLPVKWMAPESIFDCVYTVQSDVWSYGILLWEIFSLGLNPYPGILVNNFYKLVKDGYQMAQPVFAPKNIYSIMQSCWDLEPTHRPTFQQICSFLAA()}*

$2=328(261):
>XP_005380644.1  {|579(73)|}PREDICTED: macrophage colony-stimulating factor 1 receptor [Chinchilla lanigera] 
{()LQFGKTLGAGAFGKVVEATAFGLGkeDAVLKVAVKMLKSTAHADEKEALMSELKIMSHLgQHENIVNLLGACT-hGGPVLVITEYCCYGDLLNFLRKKAEamlgpslnpgqdpegdtgyknihlekkyvrrdsgfssqgldtyvemrpvstssdsfseqdldkeeKRPLELWDLLHFSSQVAQGMAFLASKNCIHRDVAARNVLLTNGHVAKIGDFGLARDIMNDSNYIVKGNARLPVKWMAPESIFDCVYTVQSDVWSYGILLWEIFSLGLNPYPGILVNSkFYKLVKDGYQMAQPAFAPKNIYSIMQACWDLEPTHRPTFQQICSLL--()}*

_0].
[0_(1)=Flt3_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Flt3_TK consensus 
{()LEFGKVLGSGAFGRVMNATAYGISGVSIQVAVKMLKEKADSCEREALMSELKMMTHLHHDNIVNLLGACTLSGPIYLIFEYCCYGDLLNYLRSKRELNVLTFEDLLCFAYQVAKGMEFLEFKSCVHRDLAARNVLVTHGKVVKICDFGLARDIMSDSNYVVRGNARLPVKWMAPESLFEGIYTIKSDVWSYGILLWEIFSLGVNPYPGIPVDNFYKLIQNGFKMDQPFYATEEIYIIMQSCWAFDSRKRPSFPNLTSFLGC()}*

$2=336(261):
>XP_012882731.1  {|608(48)|}PREDICTED: receptor-type tyrosine-protein kinase FLT3 [Dipodomys ordii] 
{()LEFGKVLGSGAFGKVMNATAYGISktGVSIQVAVKMLKEKADSSEREALMSELKMMTHLgHHENIVNLLGACTLSGPVYLIFEYCCYGDLLNYLRSKREkfhrtwteifkdnnfsfyptfqshpsssmpgsrevqihqdldqisgfngnsinsedeveyenqkrleeeedLNVLTFEDLLCFAYQVAKGMEFLEFKSCVHRDLAARNVLVTHGKVVKICDFGLARDILSDSNYVVRGNARLPVKWMAPESLFEGIYTIKSDVWSYGILLWEIFSLGVNPYPGIPVDaNFYKLIQSGFKMDQPFYATEEIYFIMQSCWAFDSRKRPSFPNLTSFLGC()}*

_0].
[0_(1)=Tie_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Tie_TK consensus 
{()ITFQDVIGEGNFGQVIKAMIKAKDGLKMNAAIKMLKEYASENDHRDFAGELEVLCKLHHPNIINLLGACEHRGYLYIAIEYAPHGNLLDFLRKSRVASTLSSQQLLHFAADVANGMQYLSQKQFIHRDLAARNILVGENYVCKIADFGLSRGAAAQEVYVKKTMGRLPVRWMAIESLNYSVYTTKSDVWSFGVLLWEIVSLGGTPYCGMTCAELYEKLPQGYRMEQPRNCDDEVYDLMRQCWRDKPYERPPFAQIAVQLNR()}*

$2=271(261):
>XP_004871907.1  {|847(29)|}tyrosine-protein kinase receptor Tie-1 isoform X1 [Heterocephalus glaber] 
{()ITFEDLIGEGNFGQVIRAMIK-KDGLKMNAAIKMLKEYASENDHRDFAGELEVLCKLgHHPNIINLLGACENRGYLYIAIEYAPYGNLLDFLRKSRVletdpafarehgtASTLSSQQLLRFASDAANGMQYLSEKQFIHRDLAARNVLVGENLASKIADFGLSRG---EEVYVKKTMGRLPVRWMAIESLNYSVYTTKSDVWSFGVLLWEIVSLGGTPYCGMTCAELYEKLPQGYRMEQPRNCDDEVYELMRQCWRDRPYERPPFAQIALQLGR()}*

_0].
[0_(1)=EGFR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>EGFR_TK consensus 
{()LKKVKVLGSGAFGTVYKGIWIPEGNVKIPVAIKVLRENTSPKANKEFLDEAYVMASVDHPHVVRLLGICLTSATVQLVTQLMPLGCLLDYVREHKDAANIGSQLLLNWCVQIAKGMSYLEERRLVHRDLAARNVLVKSPNHVKITDFGLAKLLEPEKEYHADGAGKVPIKWMALESIHFRKFTHQSDVWSYGVTVWELMTFGAKPYDGIPAREIPDLLEKGERLPQPPICTIDVYMIMVKCWMIDADSRPTFKELANEFSR()}*

$2=259(261):
>NP_034284.1  {|717(316)|}receptor tyrosine-protein kinase erbB-4 precursor [Mus musculus] 
{()LKRVKVLGSGAFGTVYKGIWVPEGeTVKIPVAIKILNETTGPKANVEFMDEALIMASMDHPHLVRLLGVCLSP-TIQLVTQLMPHGCLLDYVHEHKD--NIGSQLLLNWCVQIAKGMMYLEERRLVHRDLAARNVLVKSPNHVKITDFGLARLLEGdEKEYNADG-GKMPIKWMALECIHYRKFTHQSDVWSYGVTIWELMTFGGKPYDGIPTREIPDLLEKGERLPQPPICTIDVYMVMVKCWMIDADSRPKFKELAAEFSR()}*

_0].
[0_(1)=Axl_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Axl_TK consensus 
{()LTLGKTLGEGEFGSVMEGQLKQEDGSFLKVAVKTMKIDITQSEIEEFLSEAACMKEFDHPNVIRLIGVCFSSPIPMVILPFMKHGDLHTFLLYSRLPFNLPLQTLVKFMVDIACGMEYLSNRNFIHRDLAARNCMLNEDMTVCVADFGLSKKIYSGDYYRQGRIAKMPVKWIAIESLADRVYTSKSDVWAFGVTMWEIATRGQTPYPGVENHEIYDYLIHGNRLKQPPDCLDELYDLMYQCWSADPKDRPSFTCLRMQLEN()}*

$2=270(261):
>XP_004651823.2  {|588(137)|}PREDICTED: tyrosine-protein kinase Mer [Jaculus jaculus] 
{()LILGKILGEGEFGSVMEGNLKQEDGTSQKVAVKTMKLDNfSQREIEEFLSEAACMKDFSHPNVIRLLGVCIeMSsqgiPKPMVILPFMKYGDLHTYLLYSRLetgPKHIPLQTLLKFMVDIALGMEYLSNRNFLHRDLAARNCMLRDDMTVCVADFGLSKKIYSGDYYRQGRIAKMPVKWIAIESLADRVYTSKSDVWAFGVTMWEIATRGMTPYPGVQNHEMYDYLLHGHRLKQPEDCLDELYDIMYSCWSADPLDRPTFSVLRLQLEK()}*

_0].
[0_(1)=Met_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Met_TK consensus 
{()VHFNEVIGQGHFGCVYHGTYTDNAGNKIHCAVKSLNRITDIQEVSQFLREGIIMKDFSHPNVLSLIGICLPEGSPWVVLPYMKHGDLKNFIRNPQNAAAAAARQLISFGLQVAKGMKYLASQKFVHRDLAARNCMLDEKFTVKVADFGLARDMYDKEYYSVHTGAKLPVKWMALESLQTQKFTTKSDVWSFGVLLWELLTRGAPPYPHVNNFDITHYLAQGRRLPQPEYCPDSLYEVMLCCWHAKPAMRPSFSELVSRISQ()}*

$2=261(261):
>NP_032617.2  {|1075(43)|}hepatocyte growth factor receptor precursor [Mus musculus] 
{()VHFNEVIGRGHFGCVYHGTLLDNDGKKIHCAVKSLNRITDIEEVSQFLTEGIIMKDFSHPNVLSLLGICLRsEGSPLVVLPYMKHGDLRNFIRNETHnptvkd--------LIGFGLQVAKGMKYLASKKFVHRDLAARNCMLDEKFTVKVADFGLARDMYDKEYYSVHnkTGAKLPVKWMALESLQTQKFTTKSDVWSFGVLLWELMTRGAPPYPDVNTFDITIYLLQGRRLLQPEYCPDALYEVMLKCWHPKAEMRPSFSELVSRIS-()}*

_0].
[0_(1)=Ryk_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Ryk_TK consensus 
{()ITLKDVLQEGTFGRIYHGILNDEPNKEQQVFVKTVKDHASEIQVTLLLQESCLLYGASHRNILPVLHVCIEGEKPFVLYPHMNWGNLKQFLRQCRPAQAISTRQLVHMAIQIAMGMSYLHKHGVVHKDIAARNCVIDDTLQVKITDSALSRDLFPMDYHCLGDNENRPVKWMSLESLQNNEFSSASDVWAFGVTLWELMTLGQTPYAEIDPFEMAHYLKDGYRLAQPFNCPDELFTVMACCWALDPEERPKFQQLVQCLTE()}*

$2=269(261):
>XP_024421549.1  {|254(9)|}tyrosine-protein kinase RYK, partial [Desmodus rotundus] 
{()ITLKDVLQEGTFGRIFHGILIDEkdPNKEKQAFVKTVKDQASEIQVTMMLTESCKLRGLHHRNLLPITHVCIEeGEKPMVILPHMNWGNLKLFLRQCKlveAnnPQAISQQDLVHMAIQIACGMSYLARREVIHKDLAARNCVIDDTLQVKITDNALSRDLFPMDYHCLGDNENRPVRWMALESLVNNEFSSASDVWAFGVTLWELMTLGQTPYVDIDPFEMAAYLKDGYRIAQPINCPDELFAVMACCWALDPEERPKFQQLVQCLTE()}*

_0].
[0_(1)=InsRL_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>InsRL_TK consensus 
{()LTLIRELGEGAFGEVYLGEAYGLLESPTLVAVKTLKESASPQERLDFLREAELMSKLNHPNIVRLLGVCTEGQPLLMVFEYMEHGDLKSFLRSHRPPPPLTLSDLLHMAAQIAAGMAYLSSNHFVHRDLAARNCLVGEDLTVKIGDFGMSRDIYSTDYYRKGGKALLPIRWMAPESIMDGKFTTKSDVWSFGVVLWEIFTLGEQPYPGLSNEEVLEFVTAGGRLPPPENCPDEVYELMTRCWQREPKQRPSFKDIHERLQD()}*

$2=269(261):
>XP_012259968.1  {|215(53)|}muscle, skeletal receptor tyrosine-protein kinase-like [Athalia rosae] 
{()VVFLQDIGEGCFGKVYKGE---LRhgEVTETVAVKVLKDSASREAEENFMREVEIMSAFRHPNILFLIGVVLRDanNNPWMVFEHMPHGDLAEVLRANsRQlrcptpgLPPLTQDSLLRISTQIAAGMTYLSAQRFVHRDLACRNCLVGSELTVKIADFGMSRDVYTCDYYKIGGSRLLPIRWMAPESVIFGRFTLESDVWSFGVVLWEVYSFGKQPYYGHNNDEVVKLILHGIMLIPPEDCPPFICDIMRGCWKTEPKDRLKFTDIMEKLE-()}*

_0].
[0_(1)=Ror_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Ror_TK consensus 
{()VRFMEELGECTFGKVYKGHLYGPNHATQAVAIKTLKDKANPQQRTEFRQEASLMATLHHPNIVCLLGVVTKDQPLCMLFEYCNHGDLHEFLIMRSPKSSLDHPDFLHIAIQIAAGMEYLSSHHFVHKDLAARNCLVGDQLNVKISDFGLSREIYSADYYKVQSKSLLPIRWMPPEAIMYGKFSSDSDIWSFGVVLWEIFSYGLQPYYGYSNQEVIEMIRNRQLLPCPDDCPTWVYALMTECWNEIPSRRPRFKDIHSRLRS()}*

$2=276(261):
>XP_012876007.1  {|409(189)|}PREDICTED: tyrosine-protein kinase transmembrane receptor ROR1 isoform X1 [Dipodomys ordii] 
{()VRFMEELGECTFGKIYKGHLYLPGmdHA-QLVAIKTLKDYNNPQQWTEFQQEASLMAELHHPNIVCLLGAVTQEQPVCMLFEYMNQGDLHEFLIMRSPhsdvgcssdedgtvKSSLDHGDFLHIAIQIAAGMEYLSSHFFVHKDLAARNILIGEQLHVKISDLGLSREIYSADYYRVQSKSLLPIRWMPPEAIMYGKFSSDSDIWSFGVVLWEIFSFGLQPYYGFSNQEVIEMVRKRQLLPCSEDCPPRMYSLMTECWNEIPSRRPRFKDIHIRLRS()}*

_0].
[0_(1)=Trk_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Trk_TK consensus 
{()IVLKRELGEGAFGKVFLAECYNLCQDKMLVAVKALKDAASDNARKDFQREAELLTNLQHEHIVKFYGVCTDGDPLIMVFEYMKHGDLNKFLRAHGPPGPLGLSQMLHIASQIAAGMVYLASQHFVHRDLATRNCLVGQNLLVKIGDFGMSRDVYSTDYYRVGGHTMLPIRWMPPESIMYRKFTTESDVWSFGVVLWEIFTYGKQPWYQLSNTEVIECITQGRVLERPRTCPQEVYDIMLGCWQREPQQRKNIKDIHTILQA()}*

$2=272(261):
>XP_002721319.1  {|537(13)|}PREDICTED: BDNF/NT-3 growth factors receptor isoform X1 [Oryctolagus cuniculus] 
{()IVLKRELGEGAFGKVFLAECYNLCpeQDKILVAVKTLKD-ASDNARKDFHREAELLTNLQHEHIVKFYGVCVEGDPLIMVFEYMKHGDLNKFLRAHGPdavlmaegtpPTELTQSQMLHIAQQIAAGMVYLASQHFVHRDLATRNCLVGENLLVKIGDFGMSRDVYSTDYYRVGGHTMLPIRWMPPESIMYRKFTTESDVWSLGVVLWEIFTYGKQPWYQLSNNEVIECITQGRVLQRPRTCPQEVYELMLGCWQREPHMRKSIKDIHTLLQN()}*

_0].
[0_(1)=Musk_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Musk_TK consensus 
{()IEYVRDIGEGAFGRVFQARAPGLVEPFTMVAVKMLKETASADMQADFQREACLMAEFDHPNIVKLLGVCAVGKPMCLLFEYMAYGDLNEFLRSMSPVPPLSCAEQLCMARQIAAGMAYLSERKFVHRDLATRNCLINETMVVKIADFGLSRNIYSADYYKGDENDAIPIRWMPPESIWYNRFTTESDVWAYGVCLWEIFSYGLQPYYGMAHEEVIYYTRDGNILSCPENTPQEVYNLMRLCWSKKPADRPSFTSIHRILQR()}*

$2=284(261):
>XP_001146498.1  {|574(11)|}muscle, skeletal receptor tyrosine-protein kinase isoform X3 [Pan troglodytes] 
{()IEYVRDIGEGAFGRVFQARAPGLLpyEPFTMVAVKMLKEEASADMQADFQREAALMAEFDNPNIVKLLGVCAVGKPMCLLFEYMAYGDLNEFLRSMSPhtvcslshsdlsmraqVsspgpPPLSCAEQLCIARQVAAGMAYLSERKFVHRDLATRNCLVGENMVVKIADFGLSRNIYSADYYKANENDAIPIRWMPPESIFYNRYTTESDVWAYGVVLWEIFSYGLQPYYGMAHEEVIYYVRDGNILSCPENCPVELYNLMRLCWSKLPADRPSFTSIHRILER()}*

_0].
[0_(1)=DDR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>DDR_TK consensus 
{()LRFKEKLGEGQFGEVHLCEVEGMQGHPTLVAVKMLRPDANKNARNDFLKEIKIMSRLKDPNIIRLLGVCTTDDPLCMITEYMENGDLNQFLSAHEPKPTISYPMLVHIATQIASGMKYLSSLNFVHRDLATRNCLVGKNYTIKIADFGMSRNLYSGDYYRIQGRAVLPIRWMAWESILLGKFTTASDVWAFGVTLWEVFMFREQPYSQLTDEQVIENTGEFFRLPRPPACPQSIYELMLRCWRREPKQRPSFQEIHLFLQR()}*

$2=287(261):
>XP_007113966.1  {|562(6)|}discoidin domain-containing receptor 2 isoform X2 [Physeter catodon] 
{()LTFKEKLGEGQFGEVHLCEVEGMEkfkdkdfaldvsaNHPVLVAVKMLRADANKNARNDFLKEIKIMSRLKDPNIIRLLAVCITDDPLCMITEYMENGDLNQFLSRHEPrsssfsnVPTVSYANLKFMATQIASGMKYLSSLNFVHRDLATRNCLVGKNYTIKIADFGMSRNLYSGDYYRIQGRAVLPIRWMSWESILLGKFTTASDVWAFGVTLWETFTFcQEQPYSQLSDEQVIENTGEFFRdqgrqtyLPQPAICPDSVYKLMLSCWRRDTKHRPSFQEIHLLL--()}*

_0].
[0_(1)=InsR_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>InsR_TK consensus 
{()ITIIRELGQGSFGMVYEGNAKGIVEEETRVAIKTVNENASMRERIEFLNEASVMKEFNCHHVVRLLGVVSQGQPTLVIMELMTRGDLKSYLRSLRPLPPPTLSKMIQMAAEIADGMAYLAANKFVHRDLAARNCMVAHDFTVKIGDFGMTRDIYETDYYRKGGKGLLPVRWMAPESLKDGVFTTHSDVWSFGVVLWEIATLAEQPYQGLSNEQVLKFVMDGGVLDPPENCPDQLQELMRMCWQYNPKMRPTFLEIINSLQD()}*

$2=270(261):
>ATN95165.1  {|966(99)|}Insulin-like growth factor 1 receptor, partial [Eschrichtius robustus] 
{()ITMSRELGQGSFGMVYEGVAKGVVkdEPETRVAIKTVNESASMRERIEFLNEASVMKEFNCHHVVRLLGVVSQGQPTLVIMELMTRGDLKSYLRSLRPemennpvLAPPSLSKMIQMAGEIADGMAYLNANKFVHRDLAARNCMVAEDFTVKIGDFGMTRDIYETDYYRKGGKGLLPVRWMSPESLKDGVFTTHSDVWSFGVVLWEIATLAEQPYQGLSNEQVLRFVMEGGLLDKPDNCPDMLFELMRMCWQYNPKMRPSFLEIISSIKD()}*

_0].
[0_(1)=Sev_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Sev_TK consensus 
{()LTLRRFLGSGAFGEVYEGTAKDILSGEIKVAVKTLKKGSTDQEKIEFLKEAHLMSKFNHPNIVKQLGVCLDNEPQYIILELMEGGDLLSYLRKARMGPQLTLMDLVELCVDISKGCVYLEQMHFIHRDLAARNCLVSHPRVVKIGDFGLARDIYKNDYYRKRGEGLLPVRWMAPESLMDGIFTTQSDVWSFGILCWEILTLGHQPYPAHSNFDVLNYVQAGGRLEPPRNCPDDLWNLMTQCWAQEPDQRPTFHRIQNQLQD()}*

$2=272(261):
>EAW48208.1  {|1944(131)|}v-ros UR2 sarcoma virus oncogene homolog 1 (avian), isoform CRA_a [Homo sapiens] 
{()LTLRLLLGSGAFGEVYEGTAVDILgvgSGEIKVAVKTLKKGSTDQEKIEFLKEAHLMSKFNHPNILKQLGVCLLNEPQYIILELMEGGDLLTYLRKARMatfyGPLLTLVDLVDLCVDISKGCVYLERMHFIHRDLAARNCLVSvkdyts-PRIVKIGDFGLARDIYKNDYYRKRGEGLLPVRWMAPESLMDGIFTTQSDVWSFGILIWEILTLGHQPYPAHSNLDVLNYVQTGGRLEPPRNCPDDLWNLMTQCWAQEPDQRPTFHRIQNQLQ-()}*

_0].
[0_(1)=ALK_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>ALK_TK consensus 
{()ITLIRALGHGAFGEVYEGQVSGMPSSPLQVAVKTLPEHCSEQDELDFLMEALIISKFNHQNIVRCIGVSFQSTPRFILLELMAGGDLKSFLRETRPPSSLTMKDLLQCAQDIAQGCHYLEENHFIHRDIAARNCLLGPGRVAKIGDFGMARDIYRASYYRKGGCAMLPVKWMPPEAFLDGIFTSKTDTWSFGVLLWEIFSLGYMPYPGKSNQEVLEFVTSGGRMDPPKNCPGPVYRIMTQCWQHQPEDRPNFATILERIQY()}*

$2=270(261):
>XP_023974468.1  {|1115(230)|}ALK tyrosine kinase receptor [Physeter catodon] 
{()ITLIRGLGHGAFGEVYEGQVSGMPsdQSPLQVAVKTLPEVCSEQDELDFLMEALIISKFNHQNIVRCIGVSLQALPRFILLELMAGGDLKSFLRETRPrpnqPSSLAMLDLLHVARDIACGCQYLEENHFIHRDIAARNCLLtcpGPGRVAKIGDFGMARDIYRASYYRKGGCAMLPVKWMPPEAFMEGIFTSKTDTWSFGVLLWEIFSLGYMPYPSKSNQEVLEFVTSGGRMDPPKNCPGPVYRIMTQCWQHQPEDRPNFATILERIEY()}*

_0].
[0_(1)=CCK4_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>CCK4_TK consensus 
{()LQPITTIGKGEFGEVFLAKAQGIKETETLVLVKSLQASKDEQQQLDFRREIEMFGKLNHANVVRLLGLCREAEPHYMVLEYVDWGDLKQFLRITKGPPPLTTKQKVAICNQVALGMEHLSNNRFVHKDLAARNCLISAQRQVKVSALGLSKDVYNSEYYAHFRQAWVPIRWMSPEAIFEDDFSTKSDVWAYGVFMWEVFTHGEMPHGGQANDEVLADLQAGKALPQPEGCPSKLYRLMQRCWAPNPKDRPSFSEIASALGD()}*

$2=268(261):
>XP_021042122.1  {|787(7)|}inactive tyrosine-protein kinase 7 [Mus caroli] 
{()LQPITTLGKSEFGEVFLAKAQGIEEgaTETLVLVKSLQ-SKDEQQQLDFRREVEMFGKLNHANVVRLLGLCREAEPHYMVLEYVDLGDLKQFLRISKNkdeklkSQPLSTKQKVALCSQVALGMEHVSNNRFVHKDLAARNCLISAQRQVKVSALGLSKDVYNSEYY-HFRQAWVPLRWMSPEAVLEGDFSTKSDVWAFGVLMWEVFTHGEMPHGGQADDEVLADLQAGKArLPQPEGCPSKLYRLMQRCWAPNPKDRPSFSEIASTLGD()}*

_0].
[0_(1)=Lmr_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Lmr_TK consensus 
{()LNYLQEIGSGWFGKVFLGEVHASGTSPAQVVVKELKASASPKEQMTFLKEAQPYRILQHPNVLQCLGQCVETIPYLLVMEFCPLGDLKGYLRSCRPHEGMAPDTRQRMACEIACGLAHLHKHNFVHSDLALRNCLLTSDLTVKIGDYGLAHSNYKEDYYETPDKLWVPLRWIAPENLLTVDQTKYSNIWSLGVTLWELFENGAQPYPNLSDEQVLAQVVREQDVKLPKPYSDRWYEVLQFCWALPPEQRPTAEDVHLLLTY()}*

$2=273(261):
>NP_001162174.1  {|134(963)|}serine/threonine-protein kinase LMTK1 precursor [Rattus norvegicus] 
{()LLYLKEIGHGWFGKVFLGEVH-SGVSGTQVVVKELKASASVQEQMQFLEEAQPYRALQHSNLLQCLAQCAEVTPYLLVMEFCPLGDLKGYLRSCRVTESMAPDPLtlQRMACEVACGVLHLHRHNYVHSDLALRNCLLTADLTVKVGDYGLAHCKYREDYLVTADQLWVPLRWIAPElvdevhgNLLVVDQTKTSNVWSLGVTIWELFELGAQPYPQHSDRQVLAYAVREQQLKLPKPqlqltLSDRWYEVMQFCW-LQPEQRPTAEEVHLLLSY()}*

_0].
[0_(1)=Eph_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Eph_TK consensus 
{()IKIEEVIGAGEFGEVCSGRLKLPGKREIPVAIKTLKAGYTEKQRRDFLSEASIMGQFDHPNIIRLEGVVTKSKPVMIVTEYMENGSLDSFLRKNDAAGQFTVIQLVGMLRGIAAGMKYLSDMGYVHRDLAARNILVNSNLVCKVSDFGLSRVLEDEATYTTSGAGKIPIRWTAPEAIAYRKFTSASDVWSYGIVMWEVMSYGERPYWDMSNQDVIKAIEEGYRLPPPMDCPAALHQLMLDCWQKDRNHRPKFAQIVSTLDK()}*

$2=260(261):
>XP_015717214.1  {|651(140)|}PREDICTED: ephrin type-A receptor 5 isoform X1 [Coturnix japonica] 
{()ITIERVIGAGEFGEVCSGRLKLQGKREFPVAIKTLKAGYTEKQRRDFLGEASIMGQFDHPNIIHLEGVVTKSKPVMIVTEYMENGSLDTFLKKND--GQFTVIQLVGMLRGIASGMKYLSDMGYVHRDLAARNILINSNLVCKVSDFGLSRVLEDdpEAAYTTRG-GKIPIRWTAPEAIAFRKFTSASDVWSYGIVMWEVMSYGERPYWEMTNQDVIKAVEEGYRLPPPMDCPAALHQLMLDCWQKDRNSRPKFDEIVSMLDK()}*

_0].
[0_(1)=SrcM_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>SrcM_TK consensus 
{()LTLKKKLGSGQFGEVWMGTWNAAAGNTYKVAVKTLKEGTMSPEAADFLEEAQVMKKLQHPKLVQLYGVCTREEPIYIITEYMANGSLLDYLREGEGTSKLKLPQLLDMAAQIAEGMAYLERKNYIHRDLAARNCLVGENLIVKVADFGLARLIEVDDEYTAREGAKFPIKWTAPEAANYGRFSIKSDVWSFGILLWEIVTYGRIPYPGMTNPEVLEQVERGYRMPRPHGCPESLYEIMLRCWKEDPEERPTFEYLQSFLED()}*

$2=250(261):
>4UEU_A  {|12(13)|}Chain A, Tyrosine Kinase As - A Common Ancestor Of Src And Abl 
{()ITLERKLGSGQFGEVYEGKWrN---YNI-EVAVKTLKEGTMSVE--EFLQEAQIMKKLKHPNLVQLYGVCTKEPPIYIITEYMSHGSLLDYLRDCEG-HTVNAQALLDMAAQVASGMAYLESQNFIHRDLAARNCLVGENNVVKVADFGLARLIN-EDEYTARAGAKFPIKWTAPEAISYNRFSIKSDVWAFGILLWEIFTYGQVPYPGMSGSEVIEQVERGYRMPRPQGCPEEIYELMLQCWNKSPEERPTFaETLH-----()}*

_0].
[0_(1)=SrcA_Src_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>SrcA_Src_TK consensus 
{()LRLEVRLGQGCFGEVWMGTWNAAAGTTAKVAIKTLKPGTMSPEAAAFLQEAQIMKKLRHDKLVQLYAVVSEEAPIYIVTEFMSKGSLLDFLKDGEGAKYLKLPQLVDMAAQIASGMAYIERMNYIHRDLRAANILVGENLICKIADFGLARLIEADNEYTARQGAKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELVTKGRVPYPGMNNREVLEQVERGYRMPCPQGCPESLHELMCQCWRKDPEERPTFEYLQSFLED()}*

$2=252(261):
>XP_006139100.1  {|282(15)|}tyrosine-protein kinase Yes [Pelodiscus sinensis] 
{()LRLEVKLGQGCFGEVWMGTWN---GTT-KVAIKTLKPGTMMPE--AFLQEAQIMKKLRHDKLVPLYAVVSEE-PIYIVTEFMTKGSLLDFLKEGEG-KYLKLPQLVDMAAQIADGMAYIERMNYIHRDLRAANILVGDNLVCKIADFGLARLIE-DNEYTARQGAKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELVTKGRVPYPGMVNREVLEQVERGYRMPCPQGCPESLHELMKQCWKKDPDERPTFEYIQSFLED()}*

_0].
[0_(1)=SrcB_Src_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>SrcB_Src_TK consensus 
{()LKLVKKLGAGQFGEVWMGYYNAAANHTAKVAVKTLKPGSMSPEAAAFLAEANLMKTLQHDRLVRLYAVVTQEEPIYIITEYMAKGSLLDFLKSDEGASKLSLPKLIDFSAQIAEGMAFIERRNYIHRDLRAANILVSESLCCKIADFGLARVIEADNEYTAREGAKFPIKWTAPEAINFGCFTIKSDVWSFGILLMEIVTYGRIPYPGMSNPEVIRALERGYRMPRPDNCPEELYNIMMMCWKERPEERPTFDYLQSVLDD()}*

$2=252(261):
>XP_015004754.1  {|239(13)|}PREDICTED: tyrosine-protein kinase HCK [Macaca mulatta] 
{()LKLEKKLGAGQFGEVWMATYN---KHT-KVAVKTMKPGSMSVE--AFLAEANLMKTLQHDKLVKLHAVVTKE-PIYIITEFMAKGSLLDFLKSDEG-SKQPLPKLIDFSAQIAEGMAFIEQRNYIHRDLRAANILVSASLVCKIADFGLARIIE-DNEYTAREGAKFPIKWTAPEAINFGSFTIKSDVWSFGILLMEIVTYGRIPYPGMSNPEVIRALERGYRMPRPENCPEELYNIMMRCWKNRPEERPTFEYIQSVLDD()}*

_0].
[0_(1)=Frk_Src_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Frk_Src_TK consensus 
{()LQLKRRLGSGQFGEVWEGLWNAAANTTAPVAVKTLKPGTMDPNAAAFLAEAQIMKKLRHPKLVQLYAVCSDEEPIYIITELMRHGSLLEYLQDGDGASHLKLPQLVDMAAQVASGMAYLESQNYIHRDLAARNVLVGEHNICKVADFGLARVIKVEDEYEARHGAKFPIKWTAPEAANYGKFTIKSDVWSFGILLTEIITYGRIPYPGMTNAEVLQQVDRGYRMPQPHNCPDQLYDIMLKCWHKDPQQRPTFETLHWKLED()}*

$2=252(261):
>XP_023232584.1  {|257(16)|}tyrosine-protein kinase Src42A-like [Centruroides sculpturatus] 
{()LKFVRKLGQGQFGEVWEGLWN---NTT-PVAIKTLKPGTMDPK--DFLAEAQIMKKLRHPKLVQLYAVCTLEEPIYIITELMKHGSLLEYLQ-GKG-RSLKLPQLIDMAAQIAAGMAYLESQNYIHRDLAARNILVGENNIVKIADFGLARLIK-EDEYEARVGARFPIKWTAPEAANYSKFSIKSDVWSFGILLTELVTYGRIPYPGMTNAEVLHQVEHGYRMPCPPGCPSTLYEIMLDCWHKDPMKRPTFETLQWKLED()}*

_0].
[0_(1)=Tec_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Tec_TK consensus 
{()LTFGKELGSGQFGVVHLGQWRAAAANQYDVAIKMIKEGAMSEDAADFIEEAKVMMKLQHPNLVQLYGVCIKQGPIYIVTEYMANGCLLNYLRNNQHTLFEKTDILLDMCIDVCEGMAYLEQSGFIHRDLAARNCLVGDRNIVKVSDFGMARYVLADDEYTSSVGTKFPVKWSPPEVFTHARYSSKSDVWSFGVLMWEVFSGGKMPYEAFTNSEVVEEVSQGYRLYRPKLAPSTVYDIMKRCWHEKPEGRPSFAQLLSQITE()}*

$2=251(261):
>XP_003383374.2  {|487(13)|}PREDICTED: tyrosine-protein kinase TXK-like [Amphimedon queenslandica] 
{()LSLGKELGSGQFGRVVAGQWR----NKVDVAIKMMKEGAMNED--DFIEEAKVMQKFQHDNLVKLYGVCIKQGAVYIITELMVNGCLLQYLRNNKH-LVEKTDIILDMAIQICAAMKFLEQSGFIHRDLAARNCLVGDRNIVKVGDFGLARFVT-DDEYTASEGTKFPIKWAAPEVITHARFSSKSDVWSYGILLWELWSGGKTPYPAFTNPQVLDEVLRGYRLENPKLCPPEVYDLMKKSWQANPEDRPSFAVLSDSL--()}*

_0].
[0_(1)=Abl_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Abl_TK consensus 
{()ITMKHKLGGGQYGEVYEGVWKAAAKYSLTVAVKTLKEDTMEVEAAEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMPYGNLLDYLRECNRAEEVPAVVLLYMATQISSAMSYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMTAGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYDLLEKGYRMERPEGCPPKVYELMRACWQWSPSDRPSFAEIHQAFET()}*

$2=254(261):
>XP_003339673.1  {|261(628)|}PREDICTED: tyrosine-protein kinase ABL1 isoform X1 [Monodelphis domestica] 
{()ITMKHKLGGGQYGEVYEGVWK---KYSLTVAVKTLKEDTMEVE--EFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNR-QEVNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSRLMT-GDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKNYRMERPEGCPEKVYELMRACWQWSPSDRPSFAEIHQAFET()}*

_0].
[0_(1)=SRM_Src_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>SRM_Src_TK consensus 
{()FTLCRKLGEGYFGEVWEGLWKAAAGSVAPVAIKVISDNLMHQTAADLQKEIQAMKKLRHKHIIRLHAVCSGGDPVYIITELMPKGNLQQFLRDSDGAKALPIPELLDFACQVAEGMCYLESQNYIHRDLAARNVLVGDNNTCKVGDFGLARLIKADDIYPSHDAHNIPYKWTAPEAANYRHFSQKSDVWSFGILLHEVFTYGQCPYPGMTNHETFQQIDRGYRMPCPAECPPNVHKLMLTCWCRDPEQRPCFKTLREKLNA()}*

$2=253(261):
>EAW75263.1  {|256(8)|}PTK6 protein tyrosine kinase 6, isoform CRA_b [Homo sapiens] 
{()FTLCRKLGSGYFGEVFEGLWK---DRV-QVAIKVIsRDNLLHQQ--MLQSEIQAMKKLRHKHILALYAVVSVGDPVYIITELMAKGSLLELLRDSDE-KVLPVSELLDIAWQVAEGMCYLESQNYIHRDLAARNILVGENTLCKVGDFGLARLIK-EDVYLSHD-HNIPYKWTAPEALSRGHYSTKSDVWSFGILLHEMFSRGQVPYPGMSNHEAFLRVDAGYRMPCPLECPPSVHKLMLTCWCRDPEQRPCFKALRERLSS()}*

_0].
[0_(1)=Src-Aque1_Src_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Src-Aque1_Src_TK consensus 
{()IKFSQCINAGQFGETWKGDCKAAAGKGAPVIIKTNIATNITQEAATFLDEANILKKLHHKNIISLYGVCTESYPFYIVTEPIINGNLKDYLTTNNPATPAAAAELVDIAIQVTDGMIYLGEQDYIHCDLRAENILLGDHNTVKIANFHLAQHLNAGNKYTVEKGTKLAIRWTAPEGYTLNRLSIKSDVWSFGILLWELATKGKEPYPGMTDEEVKEAVSKGYHMPIPRDCPEPFKQLMINCWKQNDDERPNFKNIFDVLYL()}*

$2=250(261):
>XP_003391605.1  {|117(3)|}PREDICTED: tyrosine-protein kinase SRK2-like, partial [Amphimedon queenslandica] 
{()IKFFQCINAGQFGETWKGDCK---DKG-PVIIKTNIATNIVQE--TFLEEANILKKLNHKNIISLYGACTESYPFYIVTEPI-NGSLKDYLTTNNP-TP---AELVAITIQVTDGMMYLGEQDYIHCDLRAENILLGDHNTVKIANFHLARHLN-GNKYwIAKKKDKLAKKWTAPEGYTLNRLSIKSDVWSFGILLWELVSKGKEPYPGMTDEEVKEAVSKGYHMPIPRDCPEPFKLLMMNCWKQNEYERPNFIHIFNILYL()}*

_0].
[0_(1)=Csk_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Csk_TK consensus 
{()LTLGQTIGKGEFGDVMQGTYQAAAAAGNKVAVKCIKCDNGTAQAAAFLAEASVMTQLQHPNLVQLLGVILHQKGLYIVTEYMSKGNLVDYLRSRGRAAVITGDCLLKFSLDVCEGMEYLESKNFVHRDLAARNILVSEDLVAKVSDFGLAKEASAAAAASNQDSGKLPVKWTAPEALRHKKFSTKSDVWSFGILLWEIYSFGRVPYPRIPLKDVVPHVEKGYRMEAPDGCPPAVYEVMKNCWHLNPARRPTFRQLREQLEH()}*

$2=248(261):
>XP_005069649.1  {|194(8)|}tyrosine-protein kinase CSK [Mesocricetus auratus] 
{()LKLLQTIGKGEFGDVMLGDYR-----GNKVAVKCIKNDA-TAQ--AFLAEASVMTQLRHSNLVQLLGVILEEKGgLYIVTEYMAKGSLVDYLRSRGR-SVLGGDCLLKFSLDVCEAMEYLEGNNFVHRDLAARNVLVSEDNVAKVSDFGLTKEAS-----STQDTGKLPVKWTAPEALREKKFSTKSDVWSFGILLWEIYSFGRVPYPRIPLKDVVPRVEKGYKMDAPDGCPPAVYEVMKNCWHLDAATRPTFLQLREQLEH()}*

_0].
[0_(1)=Fer_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Fer_TK consensus 
{()VTLGKKLGEGAFGEVYKGTLKLKGGTTVEVAVKTCKESLTREQIKEFMQEARIMRNYDHPNVVKFYGVAVLEQPLYIVMELCNGGSLDSYLRKNKNAATLPLKQKIRFCLDAAAGMEYLHSKNCIHRDIAARNCLYGEKGQVKISDFGLSREGTCGAVYKMKGLKKVPIRWLAPETLNTGIYSSKTDVWSFGVLLWEIFSNGAEPYPGMTNAEVKEKVRNGYRMPFPNHCPEELAEIMEQCWAVDPEDRPTMSDIKQELED()}*

$2=259(261):
>OZC08585.1  {|111(8)|}hypothetical protein X798_04388, partial [Onchocerca flexuosa] 
{()IELGELLGEGALSAVYKDTSK-NNERKKEVAIKVRKgRRLDREIVEQICREARIVSKLEHPNLARLYGIAISKEPIVLLMELLKDGSLDMFLIAKGP--TLSIRKKLYFCLDIASGLEFLHNNGIIHRNISARNCLM-KDMCVKISDFNLSREikkqDE---KYKMTRLKQnLPIRWLAPETLRSAIYTTKSDVFSYGVLLWEVFTNGAEPYCGMTVAEVFVNVKDGYRIPSPDAMPKQLQTLQQNCFATEVSERWSMTQIRKEIE-()}*

_0].
[0_(1)=other-Fer_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>other-Fer_TK consensus 
{()VVLGEQIGRGNFGEVYKGTLKAADNTKTPVAVKTCRETLPQDLKRKFLQEARILKQYDHPNIVKLIGVCTQKQPIYIVMELVPGGDFLTFLRTKGNAAELTTKQLVQMVGDAAAGMEYLESKNCIHRDLAARNCLVGENNVLKISDFGMSREEGCGAVYSSSGLRQIPIKWTAPEALNYGRYSSESDVWSFGILLWETFSLGSCPYPGMTNQQAREQVERGYRMPCPEHCPEEVFRIMMQCWAYDPENRPSFSDIHQELHR()}*

$2=252(261):
>XP_007231475.2  {|564(6)|}tyrosine-protein kinase Fer [Astyanax mexicanus] 
{()VILGELLGKGNFGEVFKGTLR----DKTPVAVKTCKEDLPQDLKIKFLSEARILKQYDHPNIVKLIGVCTQRQPIYIVMELVPGGDFLSFLRKKKE--DLKTKQLVKFALDAAAGMAYLELKNCIHRDLAARNCLVGENNVLKISDFGMSRQEddG---IYSSSGLKQIPIKWTAPEALNYGRYSSESDVWSYGILLWETFSLGVCPYPGMTNQQAREQVEKGYRMSCPQKCPDEVYKIMQRCWDYKPENRPKFSDIHREL--()}*

_0].
[0_(1)=nematode-Fer_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>nematode-Fer_TK consensus 
{()VTLGKKLGEGAFGEVFKGKLKLKGGKTVEVAVKTLKESATKEQIKEFMNEARLMRNLDHPNVVRFYGVAVLEEPLYLVMELCNGGSLDSYLKKNKNAATVPLDEKIRFCLQAACGLEYLHSKNCIHRDIAARNCLLSEKGQVKISDFGLSRQGTAAASYKMKKLKKVPIRWLAPETLQTGIFSPKTDVWSFGVLCWEIFTNGAEPYPGMKNAEVKAKVRNGYRMPFPNGAPPELAEIVEKCWAVNPEDRPTMSEVKRKLED()}*

$2=276(261):
>XP_001894671.1  {|121(31)|}Protein kinase domain containing protein [Brugia malayi] 
{()VIIENKIGEGEFGEVFSGKYKLPTGRVIEVAIKLAKtAETSKEKIKEMMKEARLMRNYEHPNVIRMYGVCVEHDPLLIVMELVDGGALDDFLKKNR----VSVKDKVeKMVAGGAWGVEYLHSKNCIHRDIAARNCLLTRTGIisklsstkhnqfmkrsfllhVKISDFGLSREGD---EYHMTKARRVPIKWLAPETIQRLVYTSKTDVWSYGVMVWEIFANAAEPYPGMTNAQVKEKVINGYKMPFPPEAPPWIVEVVHNyCWQLNPDMRANMGQVARRIE-()}*

_0].
[0_(1)=FAK_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>FAK_TK consensus 
{()IELNRCIGEGQFGDVHQGVYTNHKNPAINVAIKTCKNCCTDDNREKFLQEAVIMQQFDHPHIVKLIGIITAENPTWIIMELCTYGELRHFLQRNKNAASLDLATLILYAYQLSTALAYLESKNFVHRDIAARNVLVSSPDCVKLGDFGLSRYMEDSTYYKASKATKLPIKWMAPESINFRRFTTASDVWMFGVCMWEILMHGVKPFQGVKNNDVIGRIENGERLPMPPNCPPTLYSLMTQCWAYDPSDRPRFTELKCQLSD()}*

$2=289(261):
>EAW92212.1  {|382(354)|}PTK2 protein tyrosine kinase 2, isoform CRA_c [Homo sapiens] 
{()IELGRCIGEGQFGDVHQGIYMSPENPALAVAIKTCKNCTSDSVREKFLQEAchytslhwnwcryisdpnvdaaqtpgmqrtfflVTMRQFDHPHIVKLIGVIT-ENPVWIIMELCTLGELRSFLQVRKY--SLDLASLILYAYQLSTALAYLESKRFVHRDIAARNVLVSSNDCVKLGDFGLSRYMEDSTYYKASK-GKLPIKWMAPESINFRRFTSASDVWMFGVCMWEILMHGVKPFQGVKNNDVIGRIENGERLPMPPNCPPTLYSLMTKCWAYDPSRRPRFTELKAQLS-()}*

_0].
[0_(1)=Syk_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Syk_TK consensus 
{()LVADNEIGCGNFGSVKQGYYQMKKVQKITVAIKTLKNDHDPADKDEFLREANVMHQLDNPYIVRLIGICQAAESWMLVMEMAELGPLHKYLQQHREAAEITDSNVIELVHQVAMGMKYLEEKNFVHRDLAARNVLLVTRHYAKISDFGLSKALGADNYYTATTAGKWPVKWYAPECINYYKFSSKSDVWSFGVTMWEAFSYGQKPYRKMKGPEVTAFIENGERMECPPGCPPEMYALMNDCWTYDWEDRPGFTTVEQRFRN()}*

$2=256(261):
>AAH65121.1  {|366(7)|}Syk protein [Mus musculus] 
{()--EDNELGSGNFGTVKKGYYQMKKVVK-TVAVKILKNEaNDPALKDELLAEANVMQQLDNPYIVRMIGICE-AESWMLVMEMAELGPLNKYLQQNR---HIKDKNIIELVHQVSMGMKYLEESNFVHRDLAARNVLLVTQHYAKISDFGLSKALRADeNYYKAQTHGKWPVKWYAPECINYYKFSSKSDVWSFGVLMWEAFSYGQKPYRGMKGSEVTAMLEKGERMGCPAGCPREMYDLMNLCWTYDVENRPGFTAVELRLRN()}*

_0].
[0_(1)=Jak_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Jak_TK consensus 
{()LKKIRDLGKGHFGSVELCRYDPNGNTGEQVAVKALQHSCGPQHQRDFQREIEILRTLYHDNIVKYKGVCYDRNSLKLIMEYLPSGSLRDYLQKHKNAARINHKQLLLFASQICKGMEYLGARRYIHRDLAARNILVENENHVKIGDFGLAKALPTDEYYTVKEPGDSPIFWYAPECLSECKFSIASDVWSFGVTLYELFTYGDSTQGQMTVTRLLELLKEGERLPRPPNCPDEIYHLMTNCWETNPSNRPSFQNLIPILDA()}*

$2=277(261):
>XP_010589628.1  {|843(3)|}tyrosine-protein kinase JAK1 [Loxodonta africana] 
{()LKRIRDLGEGHFGKVELCRYDPEGdNTGEQVAVKSLKPESGGNHIADLKKEIEILRNLYHENIVKYKGICTEDggNGIKLIMEFLPSGSLKEYLPKNKN--KINLKQQLKYAVQICKGMDYLGSRQYVHRDLAARNVLVESEHQVKIGDFGLTKAIETDkEYYTVKDDRDSPVFWYAPECLIQCKFYIASDVWSFGVTLHELLTYCDSdsspmalflkmigpTHGQMTVTRLVNTLKEGKRLPCPPNCPDEVYHLMRKCWEFQPSNRTTFQNLIEGFEA()}*

_0].
[0_(1)=JakB_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>JakB_TK consensus 
{()IIQNEHLGQGTFTKIYRGTLRDGEGHKTEVLLKVLDPSAHRNISEAFFEAASLMSQVSHKHLVLLYGVCVRGDENIMVQEFVEHGPLDMYLRKNGHRGCVTMPWKLQVAKQLASALSYLEDKNLVHGNVCAKNILLAREPFIKLSDPGISPTVGITVLSREELQERIRIPWVAPECLDNPNLSLAADKWSFGTTLWEICSGGEIPLSALDPQEKEQFYEDRHQLPAPKWCPQELANLITQCMNYDPNQRPSFRAILRDLNK()}*

$2=261(261):
>XP_012309976.1  {|544(327)|}tyrosine-protein kinase JAK2 isoform X1 [Aotus nancymaae] 
{()LIFNESLGQGTFTKIFKGIRREvgdyGQLHETEVLLKVLD-KAHRNYSESFFEAASMMSQLSHKHLVLNYGVCVCGEENILVQEFVKFGSLDTYLKKNKN--CINILWKLEVAKQLAWAMHFLEEKTLIHGNVCAKNILLIREedrktgnpPFIKLSDPGIS----ITVLPKDILQER--IPWVPPECIENPkNLNLATDKWSFGTTLWEICSGGDKPLSALDSQRKLQFYEDRHQLPAPKW--AELANLINNCMDYEPDFRPSFRAIIRDL--()}*

_0].
[0_(1)=Ack_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>Ack_TK consensus 
{()ITLGEKLGDGSFGVVRRGEWTNPSGKTIPVAVKCLKSDKQPGTMDDFLREVNIMHSLDHPHLVRLYGVVLATQPLMMVTELAPLGSLLDRLRKHQPAAHFLVTTLCDYAVQIAGGMAYLESKRFIHRDLAARNILLASPDKVKIGDFGLMRALPQNDYYVMQEHRKVPFAWCAPESLRTRTFSHASDVWMFGVTLWEMFSYGEEPWAGLNGSQILQKIDEGERLPRPDCCPQDIYSLMKQCWAHNPADRPTFSALRDQLQE()}*

$2=262(261):
>XP_014348226.1  {|150(682)|}PREDICTED: activated CDC42 kinase 1 [Latimeria chalumnae] 
{()ITLFEKLGDGSFGVVKRGEWCAPTGKIISVAVKCLKTDMlnQPDALDDFIWEVNAMHSLDHPNLIRLYGVVL-THPMKMVTELAPLGSLLDRLRKNQA--HFLISTLCLYAIQIANGMAYLESKRFIHRDLAARNILLASSDLIKIGDFGLMRALPKNdDHYVMQEHRKVPFAWCAPESLKTRTFSHASDTWMFGVTLWEMFTYGQEPWVGLNGSQILHKIDkEGERLPRPEDCPQDIYNVMLQCWAHKPEDRPTFMALRDFLVE()}*

_0].
[0_(1)=STYK1_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>STYK1_TK consensus 
{()LEVLEQIHSGSCGPIYRATLNTENGKTKSVILKALQDPAGLQEVQDFLGRIQFHQYLKHENLVELEGCCTDRLPLYMVLEDVSLGDLLSFLWTCRKLYDLTEKQVYHIGKQVAAALDFLQEKHLFHGDVAARNVLIQSDFTAKLCGLGLAYEVHTYGAISSTQSATVPLKWQAPERLLKRPASIRADIWSFGILLYEMITLGAPPYPEVPPSSILQHLQRRNIMKRPSSCQHAMYSIMKSCWQWNATDRPSPSELIQRLEA()}*

$2=266(261):
>NP_060893.2  {|115(41)|}tyrosine-protein kinase STYK1 [Homo sapiens] 
{()--VLEQICSGSCGPIFRANMN--TGdpsKPKSVILKALKEPAGLHEVQDFLGRIQFHQYLgKHKNLVQLEGCCTEKLPLYMVLEDVAQGDLLSFLWTCRRdvmtmdglLYDLTEKQVYHIGKQVLLALEFLQEKHLFHGDVAARNILMQSDLTAKLCGLGLAYEVYTRGAISSTQ--TIPLKWLAPERLLLRPASIRADVWSFGILLYEMVTLGAPPYPEVPPTSILEHLQRRKIMKRPSSCTHTMYSIMKSCWRWREADRPSPRELRLRLE-()}*

_0].
[0_(1)=TK-Sp1_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>TK-Sp1_TK consensus 
{()VKVRKQLGAGQFGVVYSAFADAASWKHVPVAVKMSRDNATPSMKEDFLNEIKLMFELNHPNILQIIGCCTVHEPHYLITEMMKYGDLLHFLWKCNEIYDLTQANQLQIARQIARGMEYISTTRYYHGDLAARNVLVGTGLMCKISDFGLADDIYQSGYKRLAPERKRPVKWVSLETNTQGKCTIQSDVWSFGIVLYEIYTNGGVPYPGMDGREVISKLQQGYRMEKPSNCPEDVYDIMSACWHEHPHHRPTFTNMFNFFDK()}*

$2=271(261):
>XP_011677206.1  {|430(125)|}PREDICTED: vascular endothelial growth factor receptor 1-like [Strongylocentrotus purpuratus] 
{()LKIEKELGAGQFGIVYKAFAfglnG--IKEYVPVAVKSLRVNATPGMEEDFLNEIKLMIDLgQHPNILQIIGCCTVHEPNYLITEYMKYGDLLHFLWKCREdkyrrqdsIFDLTQANQLQICRQISRGMEYIFKTRYYHGDLAARNVLVGEGLEVKVSDFGLADDIYQSGYKRLAPDKKRPVKWVSLETNTIGRCTIQSDVWSFGIVMYEIYTLGGVPYPGMDGREIISKLQEGYRMPKPDQCPEDVYDIMKACWHANPSERPTFTTIFKRLD-()}*

_0].
[0_(1)=HMTK_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>HMTK_TK consensus 
{()LKAIKQIGAGQFGKVYLAEQSVDDPEPIHRAVKLLRGDASAEDKEEFLREAEVMLQLRHPNLVQLVGVCMQQRPWLCVLEYMQYGDLRSVLKTCKENIELTLLEQLNFATQIASGMAYIASQRFVHMDLAARNCLVGSNNLVKIADFGLTRPLDEGDYWKLTTVMKLPIKWMAIEALDTKIFSEKSDVWAFGVTMWEIAAYGATPYEGIKNKEVQRAVREGLRLTQPPDCPDDFFALMCSCWEKDPSQRPTFAQLTKSLQG()}*

$2=269(261):
>XP_001742630.1  {|70(87)|}hypothetical protein, partial [Monosiga brevicollis MX1] 
{()LKPIRVLGMGQFGEVYLGLQAVKAghgengSNTIHRAVKLLKDGATPADREEFLRESELMLNFNHVNLVRLVGVAVQQRPWLCVLEYMEYGDLRAVVKAAHEkNITLTLLEQLKFAVQIATGMDYMAKHRFVHMDLAARNVLLSSKNLVKIADFGLSRKLPEErDVFVLTTSLKLPIKWMAIECMDEKIFSPASDCWALGVTMWEVAAYGMVPYPGVKNIEVQKRVREGLRLTAPEGCDPEFFELMCSCWERQPSQRPTFDQLRKSILG()}*

_0].
[0_(1)=KIN16_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>KIN16_TK consensus 
{()LEIEEPLGSGHFGVVRKGLLKMANENRLEVAVKSSANPTDISQQKMIYDELKVMCAIKHPNVLALVGAVTNKGRLMIVTEYVEGGDLRKFLRDRRNFDSLCTSDLLSFAYQIANGMEYLASVPCVHRDLALRNVLIKKNKIIRIADFGLARRHTNKDYYTKSVDTPLPIRWMAPECFEELKFTEKSDVWSYGVCLYEIFSLGESPYPNVPSYDVVEYLRNGNRLPQPEHCHPEIYDFMKLCWNFDPEDRPTFSDCVEFFEN()}*

$2=319(261):
>NP_509836.1  {|846(62)|}Tyrosine-protein kinase receptor ver-3 [Caenorhabditis elegans] 
{()LEILNPIGSGHFGVVKKGLLGMAYpkskiesKTRLPVAVKSSTNPFNVELQKMMAEELKVMCAIpKNPNVLALIGAVTkNmrQGQLYIVTEFIDGGNLREFLQAHRNtfinelvedehvpvddsylvpnsvkkkiykfdeklgegtrllvedPDALCTSDLLSIGLQIAKGMAWLADVPCVHRDLACRNVLITKTKIVRIADFGLSKKHTNKTYYrTKkSKDTPLPVRWMPLECIEEFKFTQKSDVWSFGICLYEIFTLGGTPYPNCDTFNVIEFIRNGNRNKQPEYCHDEIYELMKVCWQFNPKDRPTFNDCITFFEN()}*

_0].
[0_(1)=KIN6_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>KIN6_TK consensus 
{()IHKDKKLGSGAFGNVYKGKIKGKSYTDCQVAVKMLPSHADEAAKHDFQHEIAFMKTLHHPHLVNMLGCVTNSYPPCLVVEYCCHGDLLKYLRNYRCDTILSIKDLLQFAWQICDGMEYLHSKNFIHRDLAARNVLVTTGTTCKISDFGLCRYTDSASQYTAAKGGRLPIKWMAPECLRTYEFSTKSDVWSFGVLLFEMFSLGDVPYPTIQPTELIEHLRSGGRPAKPLWCPNEIYDIMQSCWQEKPDDRPNFTQTRMQFAT()}*

$2=321(261):
>NP_510182.1  {|463(110)|}Putative tyrosine-protein kinase F09A5.2 [Caenorhabditis elegans] 
{()VQEDHLLGNGAFANVYKGIVKGKIpllvvnnslnmtvESEnnghYEAAIKKLPAHADEQNHLDFFHEIDFMKRLgHHPHVISMLGCVSNPYEPLIVVEYCARGDLLKFLRRhkdyvlmnrvhielcisiykfklklrpnieiskisFQNktddcpieaDMCLRIKDLVSIAWQVADGMSYLASKNFIHRDLAARNILLTKSLTAKVSDFGLCRYMDS-ALYT-AKGGRLPIKWMSVEALKLYEFSTKTDVWSFGVLLFEIFSMGDVPYPTIQQVDMLEHLLAGGRLSQPLKCPNEIFNIMQKCWAEKPEDRPEFNEMRGEITV()}*

_0].
[0_(1)=REF_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>REF_TK consensus 
{()VEKEALIGEGCFGEVHQGKVCKGKQETKPVAVKLLKSSATGSEKDDFLDEIELMKCIKNSHVVNMVGCCTTQEPHCLMTEFVTHGDLLTYLRDIRQAGRLNSSDLLSFAYQIASGMEYLSSLGIVHRDLACRNILVDDGKNLKISDFGMSRMVQADDVYVKTTPGRLPLKWMAIESITDREFTTASDVWAYGVTLWEIVTLGGFPYPTVQNNELLPHLQQGYRLECPQNCSQEIYQIMLSCWHPDPQERPTFSNLRQKFDN()}*

$2=286(261):
>XP_019851309.1  {|838(187)|}PREDICTED: uncharacterized protein LOC100639009 [Amphimedon queenslandica] 
{()VILECEIGQGEFGEVYRGMLTdptvtPHTrkilketyss----SVAVKLLKPSATGSEKKDFLNEIELMKQIsqgHNSHVVNMVGCVTAQEPLCLITEFVKHGDLLSYLRATRKripedkvnpypdLGELQSSDLLSFAYQIATGMEFLSSLDIVHRDLACRNVLIGDSKNLKISDYGMSRMVQAGDTYVKSTKGKLPLKWMAIESITDREFTSASDVWAYGVTLWEIGTLGGFPYPTVGNDELLIRLKQGYRMECPDNCSKEIYDIMLECWNESPLKRPTFSVLRQKVD-()}*

_0].
[0_(1)=RTKC_TK(2){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(261)*********************************************************************************************************************************************************************************************************************************************************************

$1=261(261):
>RTKC_TK consensus 
{()LTLLDELGRGAFGIVYKALLEEPGMPGYLVACKSLHETAGGGARQELLEEAAVMAQFEHPNVVHLIGVVTVGKPILVVLEFCENGSLKSYLENNPDGAALTPVQKVRFAYQCASGMEHIHSFGFIHRDVAARNVLLSSDLTCKVADFGLARESPDDDYYRSRSAGNLPVRWTAPEALDDQKFSEKSDVWAFGILMYEIYTKAEMPYKGWSNQRVWVEVSAGFRLPCPEDCHTEVYEVMQDCWKHTPADRPTFSELVEQLRE()}*

$2=258(261):
>XP_001744118.1  {|25(0)|}hypothetical protein, partial [Monosiga brevicollis MX1] 
{()VKLLDELGRGAFGIVYKALLEEPGMPGYIVACKSLHEANQGGAMRELLEEAAVTAQFVHPNVVHLIGVVSVGKPLLVVLGFCERGSLKSYLEENgPM---VSDEQRAYFAFQCASGMEHVASFGFIHRDIAARNILLASDLSCKVSDFGLARESPNtDDshaaYYRSRS-GNLPVRWSAPEALEDQKFSHASDSWGFGILMYEIYTDAEMPYKGWSNQRVWVEVSAGFRLPRPETCHESVYEIMMDCWMHTPADRPTFSDIV-----()}*

_0].
